### PR TITLE
Adjust the text style

### PR DESCRIPTION
**Pull request by syanbo**

### CODE REVIEW

**Comment by timomeh** [comment]
Could you please describe your pull request, what it's solving, and why and what you did?

**Comment by syanbo** [comment]
I need to customize the style of the tab and the style of the label

**Comment by timomeh** [comment]
I'm planning a complete rewrite of this component, see https://github.com/timomeh/react-native-material-bottom-navigation/issues/31#issuecomment-310229009. This repo won't support custom styling, see https://github.com/timomeh/react-native-material-bottom-navigation/issues/15#issuecomment-285116249.

**Comment by syanbo** [comment]
Thank you for your help
I like this component very much

**Comment by timomeh** [comment]
I would recommend you for the time being – if you need custom styling – to use your fork instead. I won't merge it due to the reason in https://github.com/timomeh/react-native-material-bottom-navigation/issues/15#issuecomment-285116249, but I will announce the new component as soon as I implemented it.

**Pull request closed without merging**
